import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'et' | 'fr' | 'sv' | 'da' | 'no' | 'lt' | 'de' | 'es' | 'it';

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'elingohub.ai',
    tagline: 'Learn Any Language With AI',
    subtitle: 'From pronunciation to conversation — your AI tutor helps you every step',
    freeEntry: 'Free Entry',
    aiPremiumPlan: 'AI Premium Plan',
    login: 'Login',
    createAccount: 'Create Account',
    myProfile: 'My Profile',
    logout: 'Logout',
    discoverEstonia: 'Discover Estonia',
    interactiveMap: 'Interactive map with real-time facility status',
    about: 'About',
    contact: 'Contact',
    privacy: 'Privacy',
    terms: 'Terms',
    unleashYourPotential: 'Unleash Your Potential',
    poweredByAI: 'Powered by AI Technology',
    startLearningNow: 'Start Learning Now',
    noCreditCard: 'No credit card required',
    startInstantly: 'Start instantly',
    meetDeveloper: 'Meet the Developer',
    explore3DMap: 'Explore Estonia with real 3D terrain, buildings, and interactive features',
    interactiveMapLabel: 'Interactive 3D Map',
    studyEstonianMastery: 'Study the Estonian language',
    untilMastery: 'until mastery',
    chooseYourPath: 'Choose your learning path and achieve fluency with our comprehensive programs',
    startNow: 'Start Now',
    beginJourney: 'Begin your journey to Estonian mastery',
    generalEstonian: 'General Estonian for everyday life',
    businessEstonian: 'Business Estonian for entrepreneurs',
    aiPoweredLearning: 'AI-powered personalized learning',
    explorePaths: 'Explore Paths',
    joinLearners: 'Join 10,000+ learners',
    businessLanguageCourses: 'Business Language Courses',
    professionalTraining: 'Professional Language Training Programs',
    professionalTrainingDesc: 'Master business communication with our comprehensive language courses designed for professionals and enterprises',
    mostPopular: 'Most Popular',
    interactiveLessons: 'Interactive Lessons',
    realBusinessScenarios: 'Real Business Scenarios',
    aiPronunciationCoach: 'AI Pronunciation Coach',
    startLearning: 'Start Learning',
    emailWriting: 'Email & Writing Mastery',
    meetingFacilitation: 'Meeting Facilitation',
    presentationSkills: 'Presentation Skills',
    tradeCommerce: 'Trade & Commerce Focus',
    culturalIntelligence: 'Cultural Intelligence',
    negotiationTactics: 'Negotiation Tactics',
    technicalVocabulary: 'Technical Vocabulary',
    businessEtiquette: 'Business Etiquette',
    industrySpecific: 'Industry-Specific Terms',
    nordicBusiness: 'Nordic Business Culture',
    professionalNetworking: 'Professional Networking',
    businessCorrespondence: 'Business Correspondence',
    customCorporate: 'Custom Corporate Training',
    customCorporateDesc: 'Tailored language programs designed specifically for your organization\'s needs',
    customCurriculum: 'Custom Curriculum Design',
    teamProgressDash: 'Team Progress Dashboard',
    dedicatedSupport: 'Dedicated Support',
    learnMore: 'Learn More',
    readyToTransform: 'Ready to Transform Your Language Skills?',
    joinThousands: 'Join thousands of professionals mastering new languages with AI-powered training',
    startFreeTrial: 'Start Free Trial',
    viewPricing: 'View Pricing',
    aiLegalHub: 'AI Legal & Business Hub',
    aiLegalHubDesc: 'Comprehensive AI solutions for legal compliance, business education, and governance',
    professionalSolutions: 'Professional Solutions',
    trustedOrganizations: 'Trusted by leading organizations worldwide for AI-powered business solutions',
    enterpriseReady: 'Enterprise Ready',
    goPro: 'Go Pro',
    whyChoose: 'Why Choose elingohub.ai?',
    whyChooseDesc: 'The most advanced Estonian learning platform',
    aiPoweredLessons: 'AI-Powered Lessons',
    aiPoweredLessonsDesc: 'Learn with cutting-edge AI technology that adapts to your pace. Get instant feedback on pronunciation, writing, and comprehension.',
    globalCommunity: 'Global Community',
    globalCommunityDesc: 'Connect with thousands of learners and Estonian entrepreneurs. Practice in real-time chat rooms and networking lounges.',
    ai24Tutor: '24/7 AI Tutor',
    ai24TutorDesc: 'Your personal AI tutor is always available. Practice conversations, ask questions, and get help whenever you need it.',
    downloadMobileApp: 'Download the Mobile App',
    downloadMobileAppDesc: 'Learn Estonian anytime, anywhere with our mobile application. Practice with AI voice recognition on the go.',
    availableOnMobile: 'Available on Mobile',
    downloadAppStore: 'Download on the',
    appStore: 'App Store',
    getItOn: 'GET IT ON',
    googlePlay: 'Google Play',
    comingSoon: 'Coming Soon',
    learnOffline: 'Learn offline anytime, anywhere',
    trackProgress: 'Track your progress with detailed analytics',
    practiceVoice: 'Practice with AI voice recognition',
    syncDevices: 'Sync across all your devices',
    usersCount: '10,000+ Users',
    startJourneyToday: 'Start Your Estonian Journey Today',
    startJourneyDesc: 'Join thousands of learners mastering Estonian with AI',
    getStartedFree: 'Get Started Free',
    kidsForKids: 'For Kids',
    languagesForKids: 'Languages for Kids',
    adventureAcademy: 'Adventure Academy',
    funLearningAdventure: 'A fun and exciting learning adventure to master languages',
    unlockNewWorlds: 'Unlock New Worlds Through Language!',
    adventureStarts: 'Adventure starts here',
    playAndLearn: 'Play & Learn',
    learnThroughPlay: 'Learn Through Play',
    learnThroughPlayDesc: 'Fun educational games to learn 8 different languages',
    aiIntelligence: 'AI Intelligence',
    aiIntelligenceDesc: 'Interactive learning with smart AI tutor',
    rewardsChallenges: 'Rewards & Challenges',
    rewardsChallengesDesc: 'Earn points and badges while learning',
    learn8Languages: 'Learn 8 Languages Through Adventure & Games!',
    smartInvoiceAI: 'Smart Invoice AI',
    smartInvoiceDesc: 'Automate your invoicing with AI-powered smart contracts and billing systems',
    aiCoursesSpec: 'AI Courses and Specializations',
    aiCoursesSpecDesc: 'Master AI, machine learning, and data science with expert-led courses',
    aiGovernance: 'AI Governance',
    aiGovernanceDesc: 'Ensure ethical AI practices with comprehensive governance frameworks',
    automatedInvoice: 'Automated invoice generation',
    multiCurrency: 'Multi-currency support',
    taxCompliance: 'Tax compliance automation',
    paymentTracking: 'Payment tracking',
    expertCurriculum: 'Expert-led curriculum',
    handsOnProjects: 'Hands-on projects',
    industryCerts: 'Industry certifications',
    careerGuidance: 'Career guidance',
    complianceMonitoring: 'Compliance monitoring',
    riskAssessment: 'Risk assessment',
    policyFrameworks: 'Policy frameworks',
    auditTrails: 'Audit trails',
    aiAssistant: 'AI Assistant',
    welcomeMessage: 'Welcome! I\'m your AI assistant. How can I help you today? You can type your question or use the microphone to speak.',
    typeMessagePlaceholder: 'Type your message or use voice...',
    recordingSpeakNow: 'Recording... Speak now',
    stopRecording: 'Stop recording',
    startVoiceInput: 'Start voice input',
    securePayment: 'Secure Payment',
    paymentEncrypted: 'Your payment information is encrypted and secure',
    cardNumber: 'Card Number',
    cardholderName: 'Cardholder Name',
    expiryDate: 'Expiry Date',
    monthlySubscription: 'Monthly Subscription',
    billedMonthly: 'Billed monthly',
    cancelAnytime: 'Cancel anytime',
    subscribeNow: 'Subscribe Now',
    processing: 'Processing...',
    termsAgreement: 'By subscribing, you agree to our Terms of Service and Privacy Policy',
    speechNotSupported: 'Speech recognition is not supported in your browser',
    subscriptionSuccessful: 'Subscription successful for',
    learnWithAITutors: 'Learn with AI-Powered Virtual Tutors',
    chooseFavoriteTutor: 'Choose your favorite tutor and start an interactive learning journey with the best AI instructors',
    watchIntroduction: 'Watch Introduction',
    tutor: 'Tutor',
    allTutorsPowered: 'All tutors are powered by advanced AI technology to provide a personalized learning experience',
    available24: 'Available 24/7',
    previousTutors: 'Previous tutors',
    nextTutors: 'Next tutors',
  },
  et: {
    appName: 'elingohub.ai',
    tagline: 'Õpi eesti keelt AI-ga',
    subtitle: 'Hääldusest vestluseni — sinu AI õpetaja aitab sind',
    freeEntry: 'Tasuta',
    aiPremiumPlan: 'AI Premium',
    login: 'Logi sisse',
    createAccount: 'Loo konto',
    myProfile: 'Profiil',
    logout: 'Logi välja',
    discoverEstonia: 'Avasta Eestit',
    interactiveMap: 'Interaktiivne kaart',
    about: 'Meist',
    contact: 'Kontakt',
    privacy: 'Privaatsus',
    terms: 'Tingimused',
    unleashYourPotential: 'Vabasta oma potentsiaal',
    poweredByAI: 'AI tehnoloogia toel',
    startLearningNow: 'Alusta õppimist kohe',
    noCreditCard: 'Krediitkaart pole vajalik',
    startInstantly: 'Alusta kohe',
    meetDeveloper: 'Kohtu arendajaga',
    explore3DMap: 'Avasta Eesti reaalajas 3D maastiku, hoonete ja interaktiivsete funktsioonidega',
    interactiveMapLabel: 'Interaktiivne 3D kaart',
    studyEstonianMastery: 'Õpi eesti keelt',
    untilMastery: 'täiuslikkuseni',
    chooseYourPath: 'Vali õppetee ja saavuta ladusus meie põhjalike programmidega',
    startNow: 'Alusta kohe',
    beginJourney: 'Alusta oma teed eesti keele valdamiseni',
    generalEstonian: 'Üldine eesti keel igapäevaelus',
    businessEstonian: 'Äri eesti keel ettevõtjatele',
    aiPoweredLearning: 'AI-põhine personaalne õpe',
    explorePaths: 'Uuri teid',
    joinLearners: 'Liitu 10 000+ õppijaga',
    businessLanguageCourses: 'Ärikeelte kursused',
    professionalTraining: 'Professionaalsed keeleprogrammid',
    professionalTrainingDesc: 'Õpi ärikommunikatsiooni meie põhjalike keelekursustega professionaalidele ja ettevõtetele',
    mostPopular: 'Populaarseim',
    interactiveLessons: 'Interaktiivsed tunnid',
    realBusinessScenarios: 'Realistlikud äristsenaariumid',
    aiPronunciationCoach: 'AI häälduse treener',
    startLearning: 'Alusta õppimist',
    emailWriting: 'E-kirjade kirjutamine',
    meetingFacilitation: 'Koosolekute juhtimine',
    presentationSkills: 'Presenteerimisoskused',
    tradeCommerce: 'Kaubandus ja äritegevus',
    culturalIntelligence: 'Kultuuriline intelligentsus',
    negotiationTactics: 'Läbirääkimiste taktika',
    technicalVocabulary: 'Tehniline sõnavara',
    businessEtiquette: 'Ärieetikett',
    industrySpecific: 'Valdkonna-spetsiifiline',
    nordicBusiness: 'Põhjamaade ärikultuur',
    professionalNetworking: 'Professionaalne võrgustik',
    businessCorrespondence: 'Ärikirjavahetus',
    customCorporate: 'Kohandatud ettevõtte koolitus',
    customCorporateDesc: 'Teie organisatsiooni vajadustele kohandatud keelprogrammid',
    customCurriculum: 'Kohandatud õppekava',
    teamProgressDash: 'Meeskonna edusammud',
    dedicatedSupport: 'Pühendunud tugi',
    learnMore: 'Lisateave',
    readyToTransform: 'Valmis muutma oma keeleoskusi?',
    joinThousands: 'Liitu tuhandete professionaalidega, kes valdavad keeli AI-põhise koolitusega',
    startFreeTrial: 'Alusta tasuta',
    viewPricing: 'Vaata hindu',
    aiLegalHub: 'AI õigusabi ja äriteenused',
    aiLegalHubDesc: 'Terviklikud AI lahendused õigusvastavuse, ettevõtlushariduse ja juhtimise jaoks',
    professionalSolutions: 'Professionaalsed lahendused',
    trustedOrganizations: 'Usaldusväärsed AI-põhised äriteenused juhtivate organisatsioonide jaoks',
    enterpriseReady: 'Ettevõtteks valmis',
    goPro: 'Ava Premium',
    whyChoose: 'Miks valida elingohub.ai?',
    whyChooseDesc: 'Kõige arenenum eesti keele õppeplatvorm',
    aiPoweredLessons: 'AI-põhised tunnid',
    aiPoweredLessonsDesc: 'Õpi kaasaegse AI-tehnoloogia abil, mis kohandub su tempost. Saa kohest tagasisidet häälduse, kirjutamise ja mõistmise kohta.',
    globalCommunity: 'Ülemaailmne kogukond',
    globalCommunityDesc: 'Ühine tuhandete õppijate ja Eesti ettevõtjatega. Harjuta reaalajas vestlusruumides ja võrgustike salongides.',
    ai24Tutor: '24/7 AI õpetaja',
    ai24TutorDesc: 'Sinu isiklik AI õpetaja on alati saadaval. Harjuta vestlusi, küsi küsimusi ja saa abi, kui vajad.',
    downloadMobileApp: 'Laadi alla mobiilirakendus',
    downloadMobileAppDesc: 'Õpi eesti keelt igal ajal, kõikjal meie mobiilirakendusega. Harjuta AI häältuvastusega liikvel olles.',
    availableOnMobile: 'Saadaval mobiilis',
    downloadAppStore: 'Laadi alla',
    appStore: 'App Store',
    getItOn: 'HANKI',
    googlePlay: 'Google Play',
    comingSoon: 'Tuleb peagi',
    learnOffline: 'Õpi ühenduseta igal ajal, kõikjal',
    trackProgress: 'Jälgi edu üksikasjalike analüütikaga',
    practiceVoice: 'Harjuta AI häältuvastusega',
    syncDevices: 'Sünkroniseeri kõikides seadmetes',
    usersCount: '10 000+ kasutajat',
    startJourneyToday: 'Alusta oma eesti keele teekonda täna',
    startJourneyDesc: 'Liitu tuhandete õppijatega, kes valdavad eesti keelt AI abil',
    getStartedFree: 'Alusta tasuta',
    kidsForKids: 'Lastele',
    languagesForKids: 'Keeled lastele',
    adventureAcademy: 'Seiklusakaadeemia',
    funLearningAdventure: 'Lõbus ja põnev õppeseiklus keelte valdamiseks',
    unlockNewWorlds: 'Ava uued maailmad keele kaudu!',
    adventureStarts: 'Seiklus algab siin',
    playAndLearn: 'Mängi ja õpi',
    learnThroughPlay: 'Õpi mängides',
    learnThroughPlayDesc: 'Lõbusad hariduslikud mängud 8 erineva keele õppimiseks',
    aiIntelligence: 'AI intelligentsus',
    aiIntelligenceDesc: 'Interaktiivne õppimine nutika AI õpetajaga',
    rewardsChallenges: 'Auhinnad ja väljakutsed',
    rewardsChallengesDesc: 'Teeni punkte ja märke õppides',
    learn8Languages: 'Õpi 8 keelt seikluste ja mängude kaudu!',
    smartInvoiceAI: 'Nutikas arve AI',
    smartInvoiceDesc: 'Automatiseeri arveldus AI-põhiste nutikate lepingute ja arveldussüsteemidega',
    aiCoursesSpec: 'AI kursused ja spetsialiseerumised',
    aiCoursesSpecDesc: 'Õpi AI-d, masinõpet ja andmeteadust ekspertide juhitud kursustega',
    aiGovernance: 'AI juhtimine',
    aiGovernanceDesc: 'Tagada eetilised AI tavad põhjalike juhtimisraamistike abil',
    automatedInvoice: 'Automaatne arvete genereerimine',
    multiCurrency: 'Mitme valuuta tugi',
    taxCompliance: 'Maksude vastavuse automatiseerimine',
    paymentTracking: 'Maksete jälgimine',
    expertCurriculum: 'Ekspertide juhitud õppekava',
    handsOnProjects: 'Praktilised projektid',
    industryCerts: 'Tööstuse sertifikaadid',
    careerGuidance: 'Karjääri juhendamine',
    complianceMonitoring: 'Vastavuse jälgimine',
    riskAssessment: 'Riskianalüüs',
    policyFrameworks: 'Poliitika raamistikud',
    auditTrails: 'Auditi jäljed',
    aiAssistant: 'AI abiline',
    welcomeMessage: 'Tere tulemast! Olen su AI abiline. Kuidas saan sind täna aidata? Võid küsimuse sisestada või kasutada mikrofoni.',
    typeMessagePlaceholder: 'Kirjuta sõnum või kasuta häält...',
    recordingSpeakNow: 'Salvestamine... Räägi nüüd',
    stopRecording: 'Lõpeta salvestamine',
    startVoiceInput: 'Alusta häälsisestust',
    securePayment: 'Turvaline makse',
    paymentEncrypted: 'Teie makseinfo on krüpteeritud ja turvaline',
    cardNumber: 'Kaardi number',
    cardholderName: 'Kaardi omaniku nimi',
    expiryDate: 'Kehtivusaeg',
    monthlySubscription: 'Igakuine tellimus',
    billedMonthly: 'Arveldatakse igakuiselt',
    cancelAnytime: 'Tühista igal ajal',
    subscribeNow: 'Telli kohe',
    processing: 'Töötlemine...',
    termsAgreement: 'Tellides nõustute meie teenuse tingimuste ja privaatsuspoliitikaga',
    speechNotSupported: 'Kõnetuvastus ei ole teie brauseris toetatud',
    subscriptionSuccessful: 'Tellimus õnnestus',
    learnWithAITutors: 'Õpi AI-põhiste virtuaalsete õpetajatega',
    chooseFavoriteTutor: 'Vali oma lemmikõpetaja ja alusta interaktiivset õppereisi parimate AI-instruktoritega',
    watchIntroduction: 'Vaata tutvustust',
    tutor: 'Õpetaja',
    allTutorsPowered: 'Kõik õpetajad kasutavad arenenud AI-tehnoloogiat, et pakkuda personaalset õppimiskogemust',
    available24: 'Saadaval 24/7',
    previousTutors: 'Eelmised õpetajad',
    nextTutors: 'Järgmised õpetajad',
  },
  fr: { appName: 'elingohub.ai', tagline: 'Apprendre n\'importe quelle langue avec l\'IA', subtitle: 'De la prononciation à la conversation — votre tuteur IA vous aide à chaque étape', freeEntry: 'Gratuit', aiPremiumPlan: 'Plan Premium IA', login: 'Connexion', createAccount: 'Créer un compte', myProfile: 'Mon profil', logout: 'Déconnexion', discoverEstonia: 'Découvrez l\'Estonie', interactiveMap: 'Carte interactive', about: 'À propos', contact: 'Contact', privacy: 'Confidentialité', terms: 'Conditions', unleashYourPotential: 'Libérez votre potentiel', poweredByAI: 'Propulsé par la technologie IA', startLearningNow: 'Commencer maintenant', noCreditCard: 'Pas de carte de crédit requise', startInstantly: 'Commencez instantanément', meetDeveloper: 'Rencontrer le développeur', explore3DMap: 'Explorez l\'Estonie avec un terrain 3D réel, des bâtiments et des fonctionnalités interactives', interactiveMapLabel: 'Carte 3D interactive', studyEstonianMastery: 'Étudiez la langue estonienne', untilMastery: 'jusqu\'à la maîtrise', chooseYourPath: 'Choisissez votre parcours d\'apprentissage et atteignez la maîtrise avec nos programmes complets', startNow: 'Commencer maintenant', beginJourney: 'Commencez votre voyage vers la maîtrise de l\'estonien', generalEstonian: 'Estonien général pour la vie quotidienne', businessEstonian: 'Estonien des affaires pour les entrepreneurs', aiPoweredLearning: 'Apprentissage personnalisé par IA', explorePaths: 'Explorer les parcours', joinLearners: 'Rejoignez 10 000+ apprenants', businessLanguageCourses: 'Cours de langues professionnelles', professionalTraining: 'Programmes de formation linguistique professionnelle', professionalTrainingDesc: 'Maîtrisez la communication professionnelle avec nos cours de langues conçus pour les professionnels et les entreprises', mostPopular: 'Le plus populaire', interactiveLessons: 'Leçons interactives', realBusinessScenarios: 'Scénarios commerciaux réels', aiPronunciationCoach: 'Coach de prononciation IA', startLearning: 'Commencer l\'apprentissage', emailWriting: 'Maîtrise de l\'e-mail', meetingFacilitation: 'Animation de réunions', presentationSkills: 'Compétences de présentation', tradeCommerce: 'Commerce et négoce', culturalIntelligence: 'Intelligence culturelle', negotiationTactics: 'Tactiques de négociation', technicalVocabulary: 'Vocabulaire technique', businessEtiquette: 'Étiquette professionnelle', industrySpecific: 'Termes spécifiques à l\'industrie', nordicBusiness: 'Culture d\'affaires nordique', professionalNetworking: 'Réseautage professionnel', businessCorrespondence: 'Correspondance commerciale', customCorporate: 'Formation d\'entreprise personnalisée', customCorporateDesc: 'Programmes linguistiques sur mesure pour votre organisation', customCurriculum: 'Conception de curriculum personnalisé', teamProgressDash: 'Tableau de bord de progression', dedicatedSupport: 'Support dédié', learnMore: 'En savoir plus', readyToTransform: 'Prêt à transformer vos compétences linguistiques?', joinThousands: 'Rejoignez des milliers de professionnels maîtrisant de nouvelles langues', startFreeTrial: 'Commencer l\'essai gratuit', viewPricing: 'Voir les tarifs', aiLegalHub: 'Centre juridique et commercial IA', aiLegalHubDesc: 'Solutions IA complètes pour la conformité juridique, l\'éducation commerciale et la gouvernance', professionalSolutions: 'Solutions professionnelles', trustedOrganizations: 'Approuvé par les principales organisations mondiales', enterpriseReady: 'Prêt pour l\'entreprise', goPro: 'Passer à Pro', whyChoose: 'Pourquoi choisir elingohub.ai?', whyChooseDesc: 'La plateforme d\'apprentissage de l\'estonien la plus avancée', aiPoweredLessons: 'Leçons alimentées par IA', aiPoweredLessonsDesc: 'Apprenez avec une technologie IA de pointe qui s\'adapte à votre rythme', globalCommunity: 'Communauté mondiale', globalCommunityDesc: 'Connectez-vous avec des milliers d\'apprenants', ai24Tutor: 'Tuteur IA 24/7', ai24TutorDesc: 'Votre tuteur IA personnel est toujours disponible', downloadMobileApp: 'Télécharger l\'application mobile', downloadMobileAppDesc: 'Apprenez l\'estonien où que vous soyez', availableOnMobile: 'Disponible sur mobile', downloadAppStore: 'Télécharger sur', appStore: 'App Store', getItOn: 'OBTENIR SUR', googlePlay: 'Google Play', comingSoon: 'Bientôt disponible', learnOffline: 'Apprenez hors ligne', trackProgress: 'Suivez vos progrès', practiceVoice: 'Pratiquez avec la reconnaissance vocale IA', syncDevices: 'Synchronisez sur tous vos appareils', usersCount: '10 000+ utilisateurs', startJourneyToday: 'Commencez votre voyage estonien aujourd\'hui', startJourneyDesc: 'Rejoignez des milliers d\'apprenants maîtrisant l\'estonien avec l\'IA', getStartedFree: 'Commencer gratuitement', kidsForKids: 'Pour les enfants', languagesForKids: 'Langues pour enfants', adventureAcademy: 'Académie d\'aventure', funLearningAdventure: 'Une aventure d\'apprentissage amusante', unlockNewWorlds: 'Débloquez de nouveaux mondes!', adventureStarts: 'L\'aventure commence ici', playAndLearn: 'Jouer et apprendre', learnThroughPlay: 'Apprendre en jouant', learnThroughPlayDesc: 'Jeux éducatifs amusants', aiIntelligence: 'Intelligence IA', aiIntelligenceDesc: 'Apprentissage interactif', rewardsChallenges: 'Récompenses et défis', rewardsChallengesDesc: 'Gagnez des points et des badges', learn8Languages: 'Apprenez 8 langues!' },
  sv: { appName: 'elingohub.ai', tagline: 'Lär dig vilket språk som helst med AI', subtitle: 'Från uttal till konversation — din AI-lärare hjälper dig varje steg', freeEntry: 'Gratis', aiPremiumPlan: 'AI Premium Plan', login: 'Logga in', createAccount: 'Skapa konto', myProfile: 'Min profil', logout: 'Logga ut', discoverEstonia: 'Upptäck Estland', interactiveMap: 'Interaktiv karta', about: 'Om', contact: 'Kontakt', privacy: 'Integritet', terms: 'Villkor', unleashYourPotential: 'Frigör din potential', poweredByAI: 'Driven av AI-teknologi', startLearningNow: 'Börja lära dig nu', noCreditCard: 'Inget kreditkort krävs', startInstantly: 'Börja omedelbart', meetDeveloper: 'Möt utvecklaren', explore3DMap: 'Utforska Estland med verklig 3D-terräng', interactiveMapLabel: 'Interaktiv 3D-karta', studyEstonianMastery: 'Studera estniska', untilMastery: 'till behärskning', chooseYourPath: 'Välj din inlärningsväg', startNow: 'Börja nu', beginJourney: 'Börja din resa', generalEstonian: 'Allmän estniska', businessEstonian: 'Affärsestniska', aiPoweredLearning: 'AI-driven inlärning', explorePaths: 'Utforska vägar', joinLearners: 'Gå med 10,000+ elever', businessLanguageCourses: 'Affärsspråkskurser', professionalTraining: 'Professionell språkutbildning', professionalTrainingDesc: 'Bemästra affärskommunikation', mostPopular: 'Mest populär', interactiveLessons: 'Interaktiva lektioner', realBusinessScenarios: 'Verkliga affärsscenarier', aiPronunciationCoach: 'AI-uttalstränare', startLearning: 'Börja lära', emailWriting: 'E-postskrivande', meetingFacilitation: 'Mötesföring', presentationSkills: 'Presentationsfärdigheter', tradeCommerce: 'Handel', culturalIntelligence: 'Kulturell intelligens', negotiationTactics: 'Förhandlingstaktik', technicalVocabulary: 'Teknisk vokabulär', businessEtiquette: 'Affärsetik', industrySpecific: 'Branschspecifikt', nordicBusiness: 'Nordisk affärskultur', professionalNetworking: 'Professionellt nätverkande', businessCorrespondence: 'Affärskorrespondens', customCorporate: 'Anpassad företagsutbildning', customCorporateDesc: 'Skräddarsydda språkprogram', customCurriculum: 'Anpassad läroplan', teamProgressDash: 'Teamframstegspanel', dedicatedSupport: 'Dedikerad support', learnMore: 'Lär dig mer', readyToTransform: 'Redo att förändra dina språkkunskaper?', joinThousands: 'Gå med tusentals yrkesverksamma', startFreeTrial: 'Starta gratis provperiod', viewPricing: 'Visa priser', aiLegalHub: 'AI juridiskt center', aiLegalHubDesc: 'Omfattande AI-lösningar', professionalSolutions: 'Professionella lösningar', trustedOrganizations: 'Pålitlig av ledande organisationer', enterpriseReady: 'Företagsklar', goPro: 'Bli Pro', whyChoose: 'Varför välja elingohub.ai?', whyChooseDesc: 'Den mest avancerade plattformen', aiPoweredLessons: 'AI-drivna lektioner', aiPoweredLessonsDesc: 'Lär dig med banbrytande AI-teknologi', globalCommunity: 'Global gemenskap', globalCommunityDesc: 'Anslut med tusentals elever', ai24Tutor: '24/7 AI-lärare', ai24TutorDesc: 'Din personliga AI-lärare finns alltid tillgänglig', downloadMobileApp: 'Ladda ner mobilappen', downloadMobileAppDesc: 'Lär dig estniska när som helst', availableOnMobile: 'Tillgänglig på mobil', downloadAppStore: 'Ladda ner på', appStore: 'App Store', getItOn: 'FÅ DEN PÅ', googlePlay: 'Google Play', comingSoon: 'Kommer snart', learnOffline: 'Lär dig offline', trackProgress: 'Följ dina framsteg', practiceVoice: 'Öva med AI-röstigenkänning', syncDevices: 'Synka alla dina enheter', usersCount: '10,000+ användare', startJourneyToday: 'Börja din estniska resa idag', startJourneyDesc: 'Gå med tusentals elever', getStartedFree: 'Kom igång gratis', kidsForKids: 'För barn', languagesForKids: 'Språk för barn', adventureAcademy: 'Äventyrakademi', funLearningAdventure: 'Ett roligt inlärningsäventyr', unlockNewWorlds: 'Lås upp nya världar!', adventureStarts: 'Äventyret börjar här', playAndLearn: 'Lek och lär', learnThroughPlay: 'Lär genom lek', learnThroughPlayDesc: 'Roliga pedagogiska spel', aiIntelligence: 'AI-intelligens', aiIntelligenceDesc: 'Interaktivt lärande', rewardsChallenges: 'Belöningar och utmaningar', rewardsChallengesDesc: 'Tjäna poäng och märken', learn8Languages: 'Lär dig 8 språk!' },
  da: { appName: 'elingohub.ai', tagline: 'Lær ethvert sprog med AI', subtitle: 'Fra udtale til samtale — din AI-lærer hjælper dig hvert trin', freeEntry: 'Gratis', aiPremiumPlan: 'AI Premium Plan', login: 'Log ind', createAccount: 'Opret konto', myProfile: 'Min profil', logout: 'Log ud', discoverEstonia: 'Opdag Estland', interactiveMap: 'Interaktivt kort', about: 'Om', contact: 'Kontakt', privacy: 'Privatliv', terms: 'Vilkår', unleashYourPotential: 'Frigør dit potentiale', poweredByAI: 'Drevet af AI-teknologi', startLearningNow: 'Start læring nu', noCreditCard: 'Intet kreditkort påkrævet', startInstantly: 'Start øjeblikkelig', meetDeveloper: 'Mød udvikleren', explore3DMap: 'Udforsk Estland med ægte 3D-terræn', interactiveMapLabel: 'Interaktivt 3D-kort', studyEstonianMastery: 'Studér estisk', untilMastery: 'til beherskelse', chooseYourPath: 'Vælg din læringssti', startNow: 'Start nu', beginJourney: 'Begynd din rejse', generalEstonian: 'Generel estisk', businessEstonian: 'Forretningsestisk', aiPoweredLearning: 'AI-drevet læring', explorePaths: 'Udforsk stier', joinLearners: 'Tilslut dig 10,000+ elever', businessLanguageCourses: 'Forretningssprogkurser', professionalTraining: 'Professionel spraguddannelse', professionalTrainingDesc: 'Mestre forretningskommunikation', mostPopular: 'Mest populære', interactiveLessons: 'Interaktive lektioner', realBusinessScenarios: 'Virkelige forretningsscenarier', aiPronunciationCoach: 'AI-udtalelsestræner', startLearning: 'Start læring', emailWriting: 'E-mail skrivning', meetingFacilitation: 'Mødefacilitering', presentationSkills: 'Præsentationsfærdigheder', tradeCommerce: 'Handel', culturalIntelligence: 'Kulturel intelligens', negotiationTactics: 'Forhandlingstaktik', technicalVocabulary: 'Teknisk ordforråd', businessEtiquette: 'Forretningsetikette', industrySpecific: 'Branchespecifik', nordicBusiness: 'Nordisk forretningskultur', professionalNetworking: 'Professionelt netværk', businessCorrespondence: 'Forretningskorrespondance', customCorporate: 'Tilpasset virksomhedsuddannelse', customCorporateDesc: 'Skræddersyede sprogprogrammer', customCurriculum: 'Tilpasset læseplan', teamProgressDash: 'Teamfremgangspanel', dedicatedSupport: 'Dedikeret support', learnMore: 'Lær mere', readyToTransform: 'Klar til at transformere dine sprogfærdigheder?', joinThousands: 'Tilslut dig tusindvis af fagfolk', startFreeTrial: 'Start gratis prøveperiode', viewPricing: 'Se priser', aiLegalHub: 'AI juridisk center', aiLegalHubDesc: 'Omfattende AI-løsninger', professionalSolutions: 'Professionelle løsninger', trustedOrganizations: 'Betroet af førende organisationer', enterpriseReady: 'Virksomhedsklar', goPro: 'Bliv Pro', whyChoose: 'Hvorfor vælge elingohub.ai?', whyChooseDesc: 'Den mest avancerede platform', aiPoweredLessons: 'AI-drevne lektioner', aiPoweredLessonsDesc: 'Lær med banebrydende AI-teknologi', globalCommunity: 'Global fællesskab', globalCommunityDesc: 'Forbind med tusindvis af elever', ai24Tutor: '24/7 AI-lærer', ai24TutorDesc: 'Din personlige AI-lærer er altid tilgængelig', downloadMobileApp: 'Download mobilappen', downloadMobileAppDesc: 'Lær estisk når som helst', availableOnMobile: 'Tilgængelig på mobil', downloadAppStore: 'Download på', appStore: 'App Store', getItOn: 'FÅ DEN PÅ', googlePlay: 'Google Play', comingSoon: 'Kommer snart', learnOffline: 'Lær offline', trackProgress: 'Spor dine fremskridt', practiceVoice: 'Øv med AI-stemmegenkendelse', syncDevices: 'Synkroniser alle dine enheder', usersCount: '10,000+ brugere', startJourneyToday: 'Start din estiske rejse i dag', startJourneyDesc: 'Tilslut dig tusindvis af elever', getStartedFree: 'Kom i gang gratis', kidsForKids: 'For børn', languagesForKids: 'Sprog for børn', adventureAcademy: 'Eventyr akademi', funLearningAdventure: 'Et sjovt læringseventyr', unlockNewWorlds: 'Lås op for nye verdener!', adventureStarts: 'Eventyret starter her', playAndLearn: 'Leg og lær', learnThroughPlay: 'Lær gennem leg', learnThroughPlayDesc: 'Sjove pædagogiske spil', aiIntelligence: 'AI-intelligens', aiIntelligenceDesc: 'Interaktiv læring', rewardsChallenges: 'Belønninger og udfordringer', rewardsChallengesDesc: 'Tjen point og badges', learn8Languages: 'Lær 8 sprog!' },
  no: { appName: 'elingohub.ai', tagline: 'Lær ethvert språk med AI', subtitle: 'Fra uttale til samtale — din AI-lærer hjelper deg hvert trinn', freeEntry: 'Gratis', aiPremiumPlan: 'AI Premium Plan', login: 'Logg inn', createAccount: 'Opprett konto', myProfile: 'Min profil', logout: 'Logg ut', discoverEstonia: 'Oppdag Estland', interactiveMap: 'Interaktivt kart', about: 'Om', contact: 'Kontakt', privacy: 'Personvern', terms: 'Vilkår', unleashYourPotential: 'Frigjør ditt potensial', poweredByAI: 'Drevet av AI-teknologi', startLearningNow: 'Start læring nå', noCreditCard: 'Inget kreditkort kreves', startInstantly: 'Start øyeblikkelig', meetDeveloper: 'Møt utvikleren', explore3DMap: 'Utforsk Estland med ekte 3D-terreng', interactiveMapLabel: 'Interaktivt 3D-kart', studyEstonianMastery: 'Studer estisk', untilMastery: 'til mestring', chooseYourPath: 'Velg din læringssti', startNow: 'Start nå', beginJourney: 'Begynn din reise', generalEstonian: 'Generell estisk', businessEstonian: 'Forretningsestisk', aiPoweredLearning: 'AI-drevet læring', explorePaths: 'Utforsk stier', joinLearners: 'Bli med 10,000+ elever', businessLanguageCourses: 'Forretningsspråkkurser', professionalTraining: 'Profesjonell språkopplæring', professionalTrainingDesc: 'Mestre forretningskommunikasjon', mostPopular: 'Mest populær', interactiveLessons: 'Interaktive leksjoner', realBusinessScenarios: 'Virkelige forretningsscenarier', aiPronunciationCoach: 'AI-uttaletrener', startLearning: 'Start læring', emailWriting: 'E-postskriving', meetingFacilitation: 'Møtefasilitering', presentationSkills: 'Presentasjonsferdigheter', tradeCommerce: 'Handel', culturalIntelligence: 'Kulturell intelligens', negotiationTactics: 'Forhandlingstaktikk', technicalVocabulary: 'Teknisk ordforråd', businessEtiquette: 'Forretningsetikette', industrySpecific: 'Bransjespesifikk', nordicBusiness: 'Nordisk forretningskultur', professionalNetworking: 'Profesjonelt nettverk', businessCorrespondence: 'Forretningskorrespondanse', customCorporate: 'Tilpasset bedriftsopplæring', customCorporateDesc: 'Skreddersydde språkprogrammer', customCurriculum: 'Tilpasset læreplan', teamProgressDash: 'Team framgangspanel', dedicatedSupport: 'Dedikert støtte', learnMore: 'Lær mer', readyToTransform: 'Klar til å transformere språkferdighetene dine?', joinThousands: 'Bli med tusenvis av fagfolk', startFreeTrial: 'Start gratis prøveperiode', viewPricing: 'Se priser', aiLegalHub: 'AI juridisk senter', aiLegalHubDesc: 'Omfattende AI-løsninger', professionalSolutions: 'Profesjonelle løsninger', trustedOrganizations: 'Betrodd av ledende organisasjoner', enterpriseReady: 'Bedriftsklar', goPro: 'Bli Pro', whyChoose: 'Hvorfor velge elingohub.ai?', whyChooseDesc: 'Den mest avanserte plattformen', aiPoweredLessons: 'AI-drevne leksjoner', aiPoweredLessonsDesc: 'Lær med banebrytende AI-teknologi', globalCommunity: 'Global fellesskap', globalCommunityDesc: 'Koble til tusenvis av elever', ai24Tutor: '24/7 AI-lærer', ai24TutorDesc: 'Din personlige AI-lærer er alltid tilgjengelig', downloadMobileApp: 'Last ned mobilappen', downloadMobileAppDesc: 'Lær estisk når som helst', availableOnMobile: 'Tilgjengelig på mobil', downloadAppStore: 'Last ned på', appStore: 'App Store', getItOn: 'FÅ DEN PÅ', googlePlay: 'Google Play', comingSoon: 'Kommer snart', learnOffline: 'Lær offline', trackProgress: 'Spor fremgangen din', practiceVoice: 'Øv med AI-stemmegjenkjenning', syncDevices: 'Synkroniser alle dine enheter', usersCount: '10,000+ brukere', startJourneyToday: 'Start din estiske reise i dag', startJourneyDesc: 'Bli med tusenvis av elever', getStartedFree: 'Kom i gang gratis', kidsForKids: 'For barn', languagesForKids: 'Språk for barn', adventureAcademy: 'Eventyr akademi', funLearningAdventure: 'Et morsomt læringseventyr', unlockNewWorlds: 'Lås opp nye verdener!', adventureStarts: 'Eventyret starter her', playAndLearn: 'Lek og lær', learnThroughPlay: 'Lær gjennom lek', learnThroughPlayDesc: 'Morsomme pedagogiske spill', aiIntelligence: 'AI-intelligens', aiIntelligenceDesc: 'Interaktiv læring', rewardsChallenges: 'Belønninger og utfordringer', rewardsChallengesDesc: 'Tjen poeng og merker', learn8Languages: 'Lær 8 språk!' },
  lt: { appName: 'elingohub.ai', tagline: 'Mokykitės bet kurios kalbos su DI', subtitle: 'Nuo tarimo iki pokalbio — jūsų DI mokytojas padeda kiekviename žingsnyje', freeEntry: 'Nemokamai', aiPremiumPlan: 'DI Premium planas', login: 'Prisijungti', createAccount: 'Sukurti paskyrą', myProfile: 'Mano profilis', logout: 'Atsijungti', discoverEstonia: 'Atraskite Estiją', interactiveMap: 'Interaktyvus žemėlapis', about: 'Apie', contact: 'Kontaktai', privacy: 'Privatumas', terms: 'Sąlygos', unleashYourPotential: 'Išlaisvinkite savo potencialą', poweredByAI: 'Veikia DI technologija', startLearningNow: 'Pradėkite mokytis dabar', noCreditCard: 'Kredito kortelė nereikalinga', startInstantly: 'Pradėkite iš karto', meetDeveloper: 'Susipažinkite su kūrėju', explore3DMap: 'Tyrinėkite Estiją su tikra 3D reljefu', interactiveMapLabel: 'Interaktyvus 3D žemėlapis', studyEstonianMastery: 'Studijuokite estų kalbą', untilMastery: 'iki įvaldymo', chooseYourPath: 'Pasirinkite savo mokymosi kelią', startNow: 'Pradėti dabar', beginJourney: 'Pradėkite savo kelionę', generalEstonian: 'Bendrinė estų kalba', businessEstonian: 'Verslo estų kalba', aiPoweredLearning: 'DI valomas mokymasis', explorePaths: 'Tyrinėti kelius', joinLearners: 'Prisijunkite prie 10,000+ besimokančių', businessLanguageCourses: 'Verslo kalbų kursai', professionalTraining: 'Profesionalus kalbų mokymas', professionalTrainingDesc: 'Įvaldykite verslo komunikaciją', mostPopular: 'Populiariausias', interactiveLessons: 'Interaktyvios pamokos', realBusinessScenarios: 'Tikri verslo scenarijai', aiPronunciationCoach: 'DI tarimo treneris', startLearning: 'Pradėti mokytis', emailWriting: 'El. pašto rašymas', meetingFacilitation: 'Susitikimų vadovavimas', presentationSkills: 'Pristatymo įgūdžiai', tradeCommerce: 'Prekyba', culturalIntelligence: 'Kultūrinis intelektas', negotiationTactics: 'Derybų taktika', technicalVocabulary: 'Techninė terminija', businessEtiquette: 'Verslo etiketas', industrySpecific: 'Pramonei būdinga', nordicBusiness: 'Šiaurės verslo kultūra', professionalNetworking: 'Profesionalus tinklas', businessCorrespondence: 'Verslo korespondencija', customCorporate: 'Pritaikytas įmonių mokymas', customCorporateDesc: 'Pritaikytos kalbų programos', customCurriculum: 'Pritaikyta mokymo programa', teamProgressDash: 'Komandos pažangos skydelis', dedicatedSupport: 'Speciali parama', learnMore: 'Sužinoti daugiau', readyToTransform: 'Pasirengę transformuoti savo kalbos įgūdžius?', joinThousands: 'Prisijunkite prie tūkstančių profesionalų', startFreeTrial: 'Pradėti nemokamą bandomąjį laikotarpį', viewPricing: 'Peržiūrėti kainas', aiLegalHub: 'DI teisinis centras', aiLegalHubDesc: 'Išsamūs DI sprendimai', professionalSolutions: 'Profesionalūs sprendimai', trustedOrganizations: 'Patikimas pirmaujančių organizacijų', enterpriseReady: 'Paruoštas įmonėms', goPro: 'Tapti Pro', whyChoose: 'Kodėl rinktis elingohub.ai?', whyChooseDesc: 'Pažangiausia platforma', aiPoweredLessons: 'DI varomos pamokos', aiPoweredLessonsDesc: 'Mokykitės su pažangiausia DI technologija', globalCommunity: 'Pasaulinė bendruomenė', globalCommunityDesc: 'Bendrauk su tūkstančiais besimokančių', ai24Tutor: '24/7 DI mokytojas', ai24TutorDesc: 'Jūsų asmeninis DI mokytojas visada prieinamas', downloadMobileApp: 'Atsisiųsti mobiliąją programą', downloadMobileAppDesc: 'Mokykitės estų kalbos bet kada', availableOnMobile: 'Galima mobiliajame', downloadAppStore: 'Atsisiųsti iš', appStore: 'App Store', getItOn: 'GAUTI IŠ', googlePlay: 'Google Play', comingSoon: 'Netrukus', learnOffline: 'Mokytis neprisijungus', trackProgress: 'Sekti pažangą', practiceVoice: 'Praktikuotis su DI balso atpažinimu', syncDevices: 'Sinchronizuoti visuose įrenginiuose', usersCount: '10,000+ naudotojų', startJourneyToday: 'Pradėkite savo estų kalbos kelionę šiandien', startJourneyDesc: 'Prisijunkite prie tūkstančių besimokančių', getStartedFree: 'Pradėti nemokamai', kidsForKids: 'Vaikams', languagesForKids: 'Kalbos vaikams', adventureAcademy: 'Nuotykių akademija', funLearningAdventure: 'Linksmas mokymosi nuotykis', unlockNewWorlds: 'Atrakinkite naujas pasaulius!', adventureStarts: 'Nuotykis prasideda čia', playAndLearn: 'Žaisti ir mokytis', learnThroughPlay: 'Mokytis žaidžiant', learnThroughPlayDesc: 'Linksmi edukaciniai žaidimai', aiIntelligence: 'DI intelektas', aiIntelligenceDesc: 'Interaktyvus mokymasis', rewardsChallenges: 'Apdovanojimai ir iššūkiai', rewardsChallengesDesc: 'Uždirbkite taškus ir ženkliukus', learn8Languages: 'Mokykitės 8 kalbų!' },
  de: { appName: 'elingohub.ai', tagline: 'Lerne jede Sprache mit KI', subtitle: 'Von der Aussprache zur Konversation — dein KI-Tutor hilft dir bei jedem Schritt', freeEntry: 'Kostenlos', aiPremiumPlan: 'KI Premium Plan', login: 'Anmelden', createAccount: 'Konto erstellen', myProfile: 'Mein Profil', logout: 'Abmelden', discoverEstonia: 'Estland entdecken', interactiveMap: 'Interaktive Karte', about: 'Über', contact: 'Kontakt', privacy: 'Datenschutz', terms: 'Bedingungen', unleashYourPotential: 'Entfalte dein Potenzial', poweredByAI: 'Angetrieben von KI-Technologie', startLearningNow: 'Jetzt lernen starten', noCreditCard: 'Keine Kreditkarte erforderlich', startInstantly: 'Sofort starten', meetDeveloper: 'Entwickler treffen', explore3DMap: 'Erkunde Estland mit echtem 3D-Gelände', interactiveMapLabel: 'Interaktive 3D-Karte', studyEstonianMastery: 'Studiere Estnisch', untilMastery: 'bis zur Meisterschaft', chooseYourPath: 'Wähle deinen Lernpfad', startNow: 'Jetzt starten', beginJourney: 'Beginne deine Reise', generalEstonian: 'Allgemeines Estnisch', businessEstonian: 'Geschäftsestnisch', aiPoweredLearning: 'KI-gesteuertes Lernen', explorePaths: 'Pfade erkunden', joinLearners: 'Trete 10,000+ Lernenden bei', businessLanguageCourses: 'Geschäftssprachkurse', professionalTraining: 'Professionelle Sprachausbildung', professionalTrainingDesc: 'Meistere Geschäftskommunikation', mostPopular: 'Beliebteste', interactiveLessons: 'Interaktive Lektionen', realBusinessScenarios: 'Echte Geschäftsszenarien', aiPronunciationCoach: 'KI-Aussprachetrainer', startLearning: 'Lernen beginnen', emailWriting: 'E-Mail-Schreiben', meetingFacilitation: 'Sitzungsmoderation', presentationSkills: 'Präsentationsfähigkeiten', tradeCommerce: 'Handel', culturalIntelligence: 'Kulturelle Intelligenz', negotiationTactics: 'Verhandlungstaktik', technicalVocabulary: 'Technisches Vokabular', businessEtiquette: 'Geschäftsetikette', industrySpecific: 'Branchenspezifisch', nordicBusiness: 'Nordische Geschäftskultur', professionalNetworking: 'Professionelles Networking', businessCorrespondence: 'Geschäftskorrespondenz', customCorporate: 'Maßgeschneidertes Firmentraining', customCorporateDesc: 'Maßgeschneiderte Sprachprogramme', customCurriculum: 'Benutzerdefinierter Lehrplan', teamProgressDash: 'Team-Fortschrittsbereich', dedicatedSupport: 'Dedizierte Unterstützung', learnMore: 'Mehr erfahren', readyToTransform: 'Bereit, deine Sprachfähigkeiten zu transformieren?', joinThousands: 'Trete tausenden Fachleuten bei', startFreeTrial: 'Kostenlose Testversion starten', viewPricing: 'Preise ansehen', aiLegalHub: 'KI Rechtszentrum', aiLegalHubDesc: 'Umfassende KI-Lösungen', professionalSolutions: 'Professionelle Lösungen', trustedOrganizations: 'Vertraut von führenden Organisationen', enterpriseReady: 'Unternehmensbereit', goPro: 'Zu Pro wechseln', whyChoose: 'Warum elingohub.ai wählen?', whyChooseDesc: 'Die fortschrittlichste Plattform', aiPoweredLessons: 'KI-gestützte Lektionen', aiPoweredLessonsDesc: 'Lerne mit modernster KI-Technologie', globalCommunity: 'Globale Gemeinschaft', globalCommunityDesc: 'Verbinde dich mit tausenden Lernenden', ai24Tutor: '24/7 KI-Tutor', ai24TutorDesc: 'Dein persönlicher KI-Tutor ist immer verfügbar', downloadMobileApp: 'Mobile App herunterladen', downloadMobileAppDesc: 'Lerne Estnisch jederzeit', availableOnMobile: 'Verfügbar auf Mobil', downloadAppStore: 'Herunterladen bei', appStore: 'App Store', getItOn: 'JETZT BEI', googlePlay: 'Google Play', comingSoon: 'Demnächst', learnOffline: 'Offline lernen', trackProgress: 'Fortschritt verfolgen', practiceVoice: 'Üben mit KI-Spracherkennung', syncDevices: 'Auf allen Geräten synchronisieren', usersCount: '10,000+ Benutzer', startJourneyToday: 'Beginne heute deine estnische Reise', startJourneyDesc: 'Trete tausenden Lernenden bei', getStartedFree: 'Kostenlos starten', kidsForKids: 'Für Kinder', languagesForKids: 'Sprachen für Kinder', adventureAcademy: 'Abenteuer-Akademie', funLearningAdventure: 'Ein lustiges Lernabenteuer', unlockNewWorlds: 'Neue Welten erschließen!', adventureStarts: 'Das Abenteuer beginnt hier', playAndLearn: 'Spielen und lernen', learnThroughPlay: 'Durch Spielen lernen', learnThroughPlayDesc: 'Lustige Lernspiele', aiIntelligence: 'KI-Intelligenz', aiIntelligenceDesc: 'Interaktives Lernen', rewardsChallenges: 'Belohnungen und Herausforderungen', rewardsChallengesDesc: 'Punkte und Abzeichen verdienen', learn8Languages: 'Lerne 8 Sprachen!' },
  es: { appName: 'elingohub.ai', tagline: 'Aprende cualquier idioma con IA', subtitle: 'Desde la pronunciación hasta la conversación — tu tutor de IA te ayuda en cada paso', freeEntry: 'Gratis', aiPremiumPlan: 'Plan Premium IA', login: 'Iniciar sesión', createAccount: 'Crear cuenta', myProfile: 'Mi perfil', logout: 'Cerrar sesión', discoverEstonia: 'Descubre Estonia', interactiveMap: 'Mapa interactivo', about: 'Acerca de', contact: 'Contacto', privacy: 'Privacidad', terms: 'Términos', unleashYourPotential: 'Libera tu potencial', poweredByAI: 'Potenciado por tecnología IA', startLearningNow: 'Empieza a aprender ahora', noCreditCard: 'No se requiere tarjeta de crédito', startInstantly: 'Comienza al instante', meetDeveloper: 'Conoce al desarrollador', explore3DMap: 'Explora Estonia con terreno 3D real', interactiveMapLabel: 'Mapa 3D interactivo', studyEstonianMastery: 'Estudia estonio', untilMastery: 'hasta el dominio', chooseYourPath: 'Elige tu camino de aprendizaje', startNow: 'Empezar ahora', beginJourney: 'Comienza tu viaje', generalEstonian: 'Estonio general', businessEstonian: 'Estonio de negocios', aiPoweredLearning: 'Aprendizaje impulsado por IA', explorePaths: 'Explorar caminos', joinLearners: 'Únete a 10,000+ estudiantes', businessLanguageCourses: 'Cursos de idiomas de negocios', professionalTraining: 'Formación profesional de idiomas', professionalTrainingDesc: 'Domina la comunicación empresarial', mostPopular: 'Más popular', interactiveLessons: 'Lecciones interactivas', realBusinessScenarios: 'Escenarios de negocios reales', aiPronunciationCoach: 'Entrenador de pronunciación IA', startLearning: 'Comenzar aprendizaje', emailWriting: 'Redacción de correos', meetingFacilitation: 'Facilitación de reuniones', presentationSkills: 'Habilidades de presentación', tradeCommerce: 'Comercio', culturalIntelligence: 'Inteligencia cultural', negotiationTactics: 'Tácticas de negociación', technicalVocabulary: 'Vocabulario técnico', businessEtiquette: 'Etiqueta empresarial', industrySpecific: 'Específico de la industria', nordicBusiness: 'Cultura empresarial nórdica', professionalNetworking: 'Networking profesional', businessCorrespondence: 'Correspondencia empresarial', customCorporate: 'Capacitación corporativa personalizada', customCorporateDesc: 'Programas de idiomas personalizados', customCurriculum: 'Plan de estudios personalizado', teamProgressDash: 'Panel de progreso del equipo', dedicatedSupport: 'Soporte dedicado', learnMore: 'Saber más', readyToTransform: '¿Listo para transformar tus habilidades lingüísticas?', joinThousands: 'Únete a miles de profesionales', startFreeTrial: 'Iniciar prueba gratuita', viewPricing: 'Ver precios', aiLegalHub: 'Centro legal IA', aiLegalHubDesc: 'Soluciones integrales de IA', professionalSolutions: 'Soluciones profesionales', trustedOrganizations: 'Confiado por organizaciones líderes', enterpriseReady: 'Listo para empresas', goPro: 'Ir a Pro', whyChoose: '¿Por qué elegir elingohub.ai?', whyChooseDesc: 'La plataforma más avanzada', aiPoweredLessons: 'Lecciones impulsadas por IA', aiPoweredLessonsDesc: 'Aprende con tecnología IA de vanguardia', globalCommunity: 'Comunidad global', globalCommunityDesc: 'Conéctate con miles de estudiantes', ai24Tutor: 'Tutor IA 24/7', ai24TutorDesc: 'Tu tutor personal de IA siempre está disponible', downloadMobileApp: 'Descargar aplicación móvil', downloadMobileAppDesc: 'Aprende estonio en cualquier momento', availableOnMobile: 'Disponible en móvil', downloadAppStore: 'Descargar en', appStore: 'App Store', getItOn: 'CONSÍGUELO EN', googlePlay: 'Google Play', comingSoon: 'Próximamente', learnOffline: 'Aprende sin conexión', trackProgress: 'Rastrea tu progreso', practiceVoice: 'Practica con reconocimiento de voz IA', syncDevices: 'Sincroniza todos tus dispositivos', usersCount: '10,000+ usuarios', startJourneyToday: 'Comienza tu viaje estonio hoy', startJourneyDesc: 'Únete a miles de estudiantes', getStartedFree: 'Comenzar gratis', kidsForKids: 'Para niños', languagesForKids: 'Idiomas para niños', adventureAcademy: 'Academia de aventuras', funLearningAdventure: 'Una divertida aventura de aprendizaje', unlockNewWorlds: '¡Desbloquea nuevos mundos!', adventureStarts: 'La aventura comienza aquí', playAndLearn: 'Jugar y aprender', learnThroughPlay: 'Aprender jugando', learnThroughPlayDesc: 'Juegos educativos divertidos', aiIntelligence: 'Inteligencia IA', aiIntelligenceDesc: 'Aprendizaje interactivo', rewardsChallenges: 'Recompensas y desafíos', rewardsChallengesDesc: 'Gana puntos e insignias', learn8Languages: '¡Aprende 8 idiomas!' },
  it: { appName: 'elingohub.ai', tagline: 'Impara qualsiasi lingua con l\'IA', subtitle: 'Dalla pronuncia alla conversazione — il tuo tutor IA ti aiuta in ogni passo', freeEntry: 'Gratis', aiPremiumPlan: 'Piano Premium IA', login: 'Accedi', createAccount: 'Crea account', myProfile: 'Il mio profilo', logout: 'Esci', discoverEstonia: 'Scopri l\'Estonia', interactiveMap: 'Mappa interattiva', about: 'Chi siamo', contact: 'Contatti', privacy: 'Privacy', terms: 'Termini', unleashYourPotential: 'Scatena il tuo potenziale', poweredByAI: 'Alimentato dalla tecnologia IA', startLearningNow: 'Inizia ad imparare ora', noCreditCard: 'Nessuna carta di credito richiesta', startInstantly: 'Inizia subito', meetDeveloper: 'Incontra lo sviluppatore', explore3DMap: 'Esplora l\'Estonia con terreno 3D reale', interactiveMapLabel: 'Mappa 3D interattiva', studyEstonianMastery: 'Studia l\'estone', untilMastery: 'fino alla padronanza', chooseYourPath: 'Scegli il tuo percorso di apprendimento', startNow: 'Inizia ora', beginJourney: 'Inizia il tuo viaggio', generalEstonian: 'Estone generale', businessEstonian: 'Estone commerciale', aiPoweredLearning: 'Apprendimento basato su IA', explorePaths: 'Esplora percorsi', joinLearners: 'Unisciti a 10,000+ studenti', businessLanguageCourses: 'Corsi di lingue aziendali', professionalTraining: 'Formazione linguistica professionale', professionalTrainingDesc: 'Padroneggia la comunicazione aziendale', mostPopular: 'Più popolare', interactiveLessons: 'Lezioni interattive', realBusinessScenarios: 'Scenari aziendali reali', aiPronunciationCoach: 'Coach di pronuncia IA', startLearning: 'Inizia l\'apprendimento', emailWriting: 'Scrittura di email', meetingFacilitation: 'Facilitazione riunioni', presentationSkills: 'Abilità di presentazione', tradeCommerce: 'Commercio', culturalIntelligence: 'Intelligenza culturale', negotiationTactics: 'Tattiche di negoziazione', technicalVocabulary: 'Vocabolario tecnico', businessEtiquette: 'Etichetta aziendale', industrySpecific: 'Specifico del settore', nordicBusiness: 'Cultura aziendale nordica', professionalNetworking: 'Networking professionale', businessCorrespondence: 'Corrispondenza aziendale', customCorporate: 'Formazione aziendale personalizzata', customCorporateDesc: 'Programmi linguistici su misura', customCurriculum: 'Curriculum personalizzato', teamProgressDash: 'Dashboard progressi del team', dedicatedSupport: 'Supporto dedicato', learnMore: 'Saperne di più', readyToTransform: 'Pronto a trasformare le tue abilità linguistiche?', joinThousands: 'Unisciti a migliaia di professionisti', startFreeTrial: 'Inizia prova gratuita', viewPricing: 'Vedi prezzi', aiLegalHub: 'Centro legale IA', aiLegalHubDesc: 'Soluzioni IA complete', professionalSolutions: 'Soluzioni professionali', trustedOrganizations: 'Affidato dalle organizzazioni leader', enterpriseReady: 'Pronto per le aziende', goPro: 'Vai a Pro', whyChoose: 'Perché scegliere elingohub.ai?', whyChooseDesc: 'La piattaforma più avanzata', aiPoweredLessons: 'Lezioni alimentate da IA', aiPoweredLessonsDesc: 'Impara con tecnologia IA all\'avanguardia', globalCommunity: 'Comunità globale', globalCommunityDesc: 'Connettiti con migliaia di studenti', ai24Tutor: 'Tutor IA 24/7', ai24TutorDesc: 'Il tuo tutor personale IA è sempre disponibile', downloadMobileApp: 'Scarica l\'app mobile', downloadMobileAppDesc: 'Impara l\'estone in qualsiasi momento', availableOnMobile: 'Disponibile su mobile', downloadAppStore: 'Scarica su', appStore: 'App Store', getItOn: 'OTTIENILO SU', googlePlay: 'Google Play', comingSoon: 'Prossimamente', learnOffline: 'Impara offline', trackProgress: 'Traccia i tuoi progressi', practiceVoice: 'Esercitati con il riconoscimento vocale IA', syncDevices: 'Sincronizza tutti i tuoi dispositivi', usersCount: '10,000+ utenti', startJourneyToday: 'Inizia il tuo viaggio estone oggi', startJourneyDesc: 'Unisciti a migliaia di studenti', getStartedFree: 'Inizia gratis', kidsForKids: 'Per bambini', languagesForKids: 'Lingue per bambini', adventureAcademy: 'Accademia avventura', funLearningAdventure: 'Un\'avventura di apprendimento divertente', unlockNewWorlds: 'Sblocca nuovi mondi!', adventureStarts: 'L\'avventura inizia qui', playAndLearn: 'Gioca e impara', learnThroughPlay: 'Impara giocando', learnThroughPlayDesc: 'Giochi educativi divertenti', aiIntelligence: 'Intelligenza IA', aiIntelligenceDesc: 'Apprendimento interattivo', rewardsChallenges: 'Ricompense e sfide', rewardsChallengesDesc: 'Guadagna punti e badge', learn8Languages: 'Impara 8 lingue!' },
};

const LanguageContext = createContext<any>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const t = (key: string) => translations[language][key] || key;
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export const languageOptions = [
  { code: 'en' as Language, name: 'English', flag: 'gb' },
  { code: 'et' as Language, name: 'Estonian', flag: 'ee' },
  { code: 'fr' as Language, name: 'French', flag: 'fr' },
  { code: 'sv' as Language, name: 'Swedish', flag: 'se' },
  { code: 'da' as Language, name: 'Danish', flag: 'dk' },
  { code: 'no' as Language, name: 'Norwegian', flag: 'no' },
  { code: 'lt' as Language, name: 'Lithuanian', flag: 'lt' },
  { code: 'de' as Language, name: 'German', flag: 'de' },
  { code: 'es' as Language, name: 'Spanish', flag: 'es' },
  { code: 'it' as Language, name: 'Italian', flag: 'it' },
];
